services:
  - type: web
    name: flask-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class=gevent --workers=1 --timeout 180 --bind=0.0.0.0:$PORT index:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
