services:
  - type: web
    name: ctrack-locator-server
    runtime: python
    buildCommand: |
      echo "=== Python Version Check ==="
      python3 --version || python --version
      echo "=== Installing minimal dependencies first ==="
      python3 -m pip install --upgrade pip
      python3 -m pip install --no-build-isolation Flask==2.3.3 Flask-Cors==4.0.0 gunicorn==21.2.0
      echo "=== Installing remaining dependencies ==="
      python3 -m pip install --no-cache-dir --prefer-binary -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 index:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: PIP_NO_CACHE_DIR
        value: '1'
      - key: PYTHONUNBUFFERED
        value: '1'
      - key: PYTHONDONTWRITEBYTECODE
        value: '1'
