services:
  - type: web
    name: ctrack-locator-server
    runtime: python
    buildCommand: |
      python --version
      python -m pip install --upgrade pip==24.0 setuptools==69.5.1 wheel==0.43.0
      python -m pip install --no-cache-dir --only-binary=all --prefer-binary -r requirements.txt || python -m pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 index:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: PIP_NO_CACHE_DIR
        value: '1'
      - key: PYTHONUNBUFFERED
        value: '1'
      - key: PYTHONDONTWRITEBYTECODE
        value: '1'
