services:
  - type: web
    name: ctrack-locator-server
    runtime: python
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      python -m pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn --worker-class=gevent --workers=1 --timeout 180 --bind=0.0.0.0:$PORT index:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: PIP_NO_CACHE_DIR
        value: 1
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PYTHONUNBUFFERED
        value: 1
